# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: room_join.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'room_join.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0froom_join.proto\"\xaf\x03\n\tjoin_room\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x12\"\n\x07\x66ield_2\x18\x02 \x01(\x0b\x32\x11.join_room.Field2\x1a\xec\x02\n\x06\x46ield2\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x03\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\t\x12)\n\x07\x66ield_8\x18\x08 \x01(\x0b\x32\x18.join_room.Field2.Field8\x12\x0f\n\x07\x66ield_9\x18\t \x01(\t\x12\x10\n\x08\x66ield_10\x18\n \x01(\x05\x12+\n\x08\x66ield_12\x18\x0c \x01(\x0b\x32\x19.join_room.Field2.Field12\x12\x10\n\x08\x66ield_13\x18\r \x01(\x05\x12\x10\n\x08\x66ield_14\x18\x0e \x01(\x05\x12\x10\n\x08\x66ield_16\x18\x10 \x01(\t\x12+\n\x08\x66ield_22\x18\x16 \x01(\x0b\x32\x19.join_room.Field2.Field22\x1a;\n\x06\x46ield8\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\t\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\t\x1a\t\n\x07\x46ield12\x1a\x1a\n\x07\x46ield22\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_join_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOIN_ROOM']._serialized_start=20
  _globals['_JOIN_ROOM']._serialized_end=451
  _globals['_JOIN_ROOM_FIELD2']._serialized_start=87
  _globals['_JOIN_ROOM_FIELD2']._serialized_end=451
  _globals['_JOIN_ROOM_FIELD2_FIELD8']._serialized_start=353
  _globals['_JOIN_ROOM_FIELD2_FIELD8']._serialized_end=412
  _globals['_JOIN_ROOM_FIELD2_FIELD12']._serialized_start=414
  _globals['_JOIN_ROOM_FIELD2_FIELD12']._serialized_end=423
  _globals['_JOIN_ROOM_FIELD2_FIELD22']._serialized_start=425
  _globals['_JOIN_ROOM_FIELD2_FIELD22']._serialized_end=451
# @@protoc_insertion_point(module_scope)
